version: "3.2"
services:
  proxy:
    env_file: .env
    image: jupyterhub/configurable-http-proxy:3.1.1
    networks:
      - mlhub-admin
    # expose the proxy to the world
    ports:
      - "80:8000"
    command:
      - configurable-http-proxy
      - "--error-target"
      - "http://hub/hub/error"
  hub:
    env_file: .env
    image: vasiltapkin/vasilhub:latest
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: jupyterhub_data
        target: /data
        volume:
          nocopy: true
      - type: volume
        source: jupyteruser
        target: /jupyterUsers
        volume:
          nocopy: true
    networks:
      - mlhub-admin
    ports:
      - "8080:8080"
volumes:
  jupyterhub_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.99.1,nolock,soft,rw"
      device: ":/Users/vasiltapkin/Virtualbox/Volumes/data"
  jupyteruser:
    external:
      name: jupyterhub-userdata
networks:
  mlhub-admin:
    driver: overlay


